[package]
name = "alreadypro/flipper"
description = "A motion library for Roblox forked to add support for Tweens"
license = "MIT"
authors = ["AlreadyPro"]
version = "2.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]
