[package]
name = "destruction-studios/flipper"
description = "A motion library for Roact"
license = "MIT"
authors = ["AlreadyPro", "Destruction Studios"]
version = "2.0.10"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]
